name: Cypress

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm start
        env:
          CYPRESS_BASE_URL: http://localhost:3333
